### PR TITLE
project: add goreleaser configuration.

### PR DESCRIPTION
**Pull request by cpu**
Adds configuration for [GoReleaser](https://goreleaser.com/) to the project/CI.

Before this will be functional a dedicated Github user with write access to the ZLint repository needs to be created, and an API key saved into the Travis config as a protected env var named `GITHUB_AUTH_TOKEN`.

By default releases are added to the repository in draft status. This gives maintainers a chance to write the release notes/changelog and verify the build artifacts before publishing the release. Tags with "rc" in the name will be marked as pre-release candidates automatically.

Updates https://github.com/zmap/zlint/issues/351

### CODE REVIEW

**Comment by zakird** [comment]
This looks good. I held off merging in case you want to setup user and secret first.

**Comment by cpu** [comment]
>  I held off merging in case you want to setup user and secret first.

I've created the user and set up the secret but I'm blocked on Github support removing a "suspicious account" flag on the new user. I can't add it as a collaborator to the repo until that's resolved. I'll merge this once that's sorted out.

**Comment by cpu** [comment]
>  I can't add it as a collaborator to the repo until that's resolved. I'll merge this once that's sorted out.

All fixed. I added @zlintbot to the repo such that CI should be able to generate releases.

**Comment by cpu** [comment]
I had to fix the name of an env var but the automation worked correctly for the `v2.0.0-rc1` tag :tada:

https://travis-ci.org/zmap/zlint/builds/649116718 created a draft release.

**Pull request merged**
