### PR TITLE
Ocsp eku check for tls certificates

### PR DESCRIPTION
**Pull request by RufusJWB**
This PR is split from https://github.com/zmap/zlint/pull/472 to simplify the review process.

I did some sample testing on the findings on the test corpus:

- https://censys.io/certificates/01a070613aaeb102c44468a231559e3b66d1982ec6435891909a9e6b366423d2
- https://censys.io/certificates/01f8971121f4103d30be4235cd7dc0eee6c6ae12fca7750848ea0e2e13fc2428
- https://censys.io/certificates/01fd614879394b3ae149252fc15698674159ce5550669ff912892e19835a1e4c
- https://censys.io/certificates/03b5ffe7db4d85717cb2ed07119dd63a8d592c2fd04f2988d1c074f0fffaaa2e
- https://censys.io/certificates/04ecba8f92bff7458c4a5e7c69261fc7e2ef52d5af54fbdd92b17141bbe0651f

--> All the samples do look reasonable

### CODE REVIEW

**Comment by RufusJWB** [comment]
I did some sample testing.

- https://censys.io/certificates/01a070613aaeb102c44468a231559e3b66d1982ec6435891909a9e6b366423d2
- https://censys.io/certificates/01f8971121f4103d30be4235cd7dc0eee6c6ae12fca7750848ea0e2e13fc2428
- https://censys.io/certificates/01fd614879394b3ae149252fc15698674159ce5550669ff912892e19835a1e4c
- https://censys.io/certificates/03b5ffe7db4d85717cb2ed07119dd63a8d592c2fd04f2988d1c074f0fffaaa2e
- https://censys.io/certificates/04ecba8f92bff7458c4a5e7c69261fc7e2ef52d5af54fbdd92b17141bbe0651f

--> All the samples do look reasonable

**Comment by RufusJWB** [comment]
I had to close and re-open this PR to re-start the CI pipeline which failed due to external problems (https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915).

**Comment by RufusJWB** [comment]
@RufusJWB @cardonator any thoughts on this newly simplified Lint?

**Comment by RufusJWB** [comment]
@cardonator @zakird since the OCSP responder topic came up on the mdsp mailing list again, do you think we could finalize this PR?

**Comment by RufusJWB** [comment]
Is there someone willing to review?

**Comment by RufusJWB** [comment]
Do you think, you could include #490 and #491 in this version?

**Comment by christopher-henderson** [comment]
@RufusJWB this far more obvious than its sister PR and seems pretty reasonable to me. I believe that this is the more urgent of the two cases as well and would be the more immediate win.

@zakird if you give me write access to the repo then I believe I should be able to resolve the conflicts myself and merge (and run the Travis builds?).

**Comment by zakird** [comment]
I think the access problem is that this PR is based off of a branch outside of the repository. You have rights to the zlint repository itself.

**Review by cardonator — APPROVED** [review]
Thanks, @RufusJWB This was much easier to read through without the extra bloat of the other changes. Sorry it took so long for me to get back to reviewing it! 👍

**Comment by cpu** [comment]
> (and run the Travis builds?).

I think once a new commit is pushed to this branch the new branch protection settings will kick-in and realize Travis is gone. The GIthub actions should also run at that point.

**Comment by zakird** [comment]
I agree, this looks significantly simpler and more straight forward. Once we get the merge conflicts fixed, we should be in good shape.

**Comment by RufusJWB** [comment]
@zakird @cpu @cardonator @christopher-henderson  - fixed the merge conflicts. You are ready to go!

**Review by christopher-henderson — APPROVED** [review]

**Review by zakird — APPROVED** [review]

**Pull request merged**
