### PR TITLE
Update lint_ecdsa_ee_invalid_ku.go

### PR DESCRIPTION
**Pull request by ENEN-DTR**
Changed Error handling for invalidKUs

### CODE REVIEW

**Comment by zakird** [comment]
Can you provide some context around the change? Based on the RFC text, the original code looks to be correct. Nothing says that the certificate `MUST NOT` have other codes.

**Comment by ENEN-DTR** [comment]
Yes, of course. This should address issue #454 .

**Comment by zakird** [comment]
The text of this RFC seems to be rather different from what's being checked in the proposed change:

```
   If the keyUsage extension is present in a certificate that indicates
   id-ecPublicKey in SubjectPublicKeyInfo, then following values MUST
   NOT be present:

     keyEncipherment; and
     dataEncipherment.

   If the keyUsage extension is present in a certificate that indicates
   id-ecDH or id-ecMQV in SubjectPublicKeyInfo, then the following
   values also MUST NOT be present:

     keyEncipherment; and
     dataEncipherment.
```

The PR will need to check _exactly_ what's laid out in this RFC and also update the description to reference these statements.

**Comment by ENEN-DTR** [comment]
PR closed to #599

**Pull request closed without merging**
