### PR TITLE
Add a new lint to prohibit using DSA

### PR DESCRIPTION
**Pull request by robplee**
This is my attempt at addressing #537 although I expect there may be a number of changes that will be needed as this is my first attempt at adding a lint to zlint.  I created a new certificate to cover an error case but I reused some of the certs already in testdata to cover Pass and Not Effective cases.

Please let me know if and when anything needs changing :)

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Thanks @robplee, really nice work! 

I'll hold on merging this for a little while to give others a chance to review but it looks good to me.

**Comment by cpu** [comment]
> @cpu cpu closed this now
> @cpu cpu reopened this now

CI statuses looked jammed up. Gave it the ol' close/open to get things flowing again.

**Review by christopher-henderson — APPROVED** [review]
Looks great to me, thank you @robplee !

**Review by zakird — APPROVED** [review]

**Comment by sleevi** [comment]
Was the intent to only add this as a Mozilla test, or to also reflect that the BRs also now forbid this? I probably worded the issue wrong, but was trying to capture from (moz 2.4.1 effective date to BRs 1.7.1 effective date), Moz forbade it, and then onward, the BRs forbade it.

I suspect that means two separate lints (this was the question part of #537 ), and I’m fine with only tackling one of those in this :)

**Comment by zakird** [comment]
Two lints :)

**Comment by sleevi** [comment]
Yeah, sorry for confusing things yet again :) We resolved on the issue two lints, and so I just wanted to make sure this wasn’t seen as closing out the issue, since this is only one lint. But I’m definitely good with landing this lint as is, or also duplicating it (and changing the effective date) as a BR lint, which would then close #537

**Comment by christopher-henderson** [comment]
Howdy @sleevi. I'm gonna merge this and I went ahead and fired up #574 to track the similar work for the BR effective date.

**Pull request merged**
