### PR TITLE
remove lisp reserved range since no longer IANA reserved

### PR DESCRIPTION
**Pull request by zakird**
lisp range is no longer reserved here: https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml

### CODE REVIEW

**Comment by zakird** [comment]
When I was looking at this list I noticed that the loopback ranges`::1/128`, `::/128`, and `127.0.0.1/8` aren't in this set of blocks. @sleevi these cannot be used, right? @cpu do we have a lint elsewhere for these? I'm not finding one, but I feel like this has to be me missing something.

**Comment by sleevi** [comment]
> When I was looking at this list I noticed that the loopback ranges`::1/128`, `::/128`, and `127.0.0.1/8` aren't in this set of blocks. @sleevi these cannot be used, right? @cpu do we have a lint elsewhere for these? I'm not finding one, but I feel like this has to be me missing something.

Correct. They're reserved by protocol, so should not be allowed (e.g. https://tools.ietf.org/html/rfc4291#section-2.5.3 )

**Comment by zakird** [comment]
Thanks. Once this is merged, I'll add those in if there's truly no loopback lint already.

**Comment by cpu** [comment]
>  @cpu do we have a lint elsewhere for these? I'm not finding one, but I feel like this has to be me missing something.

@zakird These addresses seem to be caught by the call to `ip.IsGlobalUnicast()` at the start of `util.IsIANAReserved`:
https://github.com/zmap/zlint/blob/3329bb69d206198706abc7c84eccb59011bd9de5/v2/util/ip.go#L63-L65

I confirmed this with a tiny unit test:

```go
// util/ip_test.go 
package util

import (
	"net"
	"testing"
)

func TestBadIP(t *testing.T) {
	if !IsIANAReserved(net.ParseIP("127.0.0.1")) {
		t.Error("loopback address was not considered reserved")
	}
	if !IsIANAReserved(net.ParseIP("::1/128")) {
		t.Error("loopback address was not considered reserved")
	}
}
```

```bash
$ go test --test.run TestBadIP -v ./util/
=== RUN   TestBadIP
--- PASS: TestBadIP (0.00s)
PASS
ok  	github.com/zmap/zlint/v2/util	0.004s
```

It probably makes sense to make this more explicit in the code (with a comment, or by adding the ranges explicitly to `reservedNetworks`.

**Pull request merged**
