### PR TITLE
Update copyright to 2021

### LINKED ISSUE #542: Ring in the new year (2021)
Update copyrights.

### PR DESCRIPTION
**Pull request by christopher-henderson**
Resolves #542

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Thanks @christopher-henderson :-)

:memo: Did you use:

* `sed`
* `awk`
* robot labour
* other

It's important to know everyone's bulk editing preferences!

**Comment by christopher-henderson** [comment]
I've been enthralled with the onslaught of Rust based tooling that seeks to replace old hat Unix standards (see [ripgrep](https://github.com/BurntSushi/ripgrep) which replaces `grep` in such a big way that I can never go back and [fd](https://github.com/sharkdp/fd) which replaces `find`).

BUT....`ripgrep` doesn't do inplace replacement...

```
    -r, --replace <REPLACEMENT_TEXT>        
            Replace every match with the text given when printing results. Neither this
            flag nor any other ripgrep flag will modify your files.
```

So I did the not so nerdy thing and just did a project wide find-and-replace in GoLand :stuck_out_tongue:

**Comment by cpu** [comment]
@christopher-henderson TIL about GoLand. I've been using IntelliJ and PyCharm at work, maybe I should try GoLand too :-)

**Comment by christopher-henderson** [comment]
JetBrains knows their stuff! I look forward to their dedicated Rust IDE (it's just a plugin at the moment)

**Pull request merged**
