### PR TITLE
Update to Go 1.15, latest , fix n_san_iana_pub_suffix_empty.

### LINKED ISSUE #461: Tests failures with Go 1.15
Using zlint 1.1.0 with Go 1.15 rc 1 on Fedora Rawhide, I get these errors:

```
ok  	github.com/zmap/zlint	0.220s
github.com/zmap/zlint/lints
asn1: structure error: tags don't match (6 vs {class:2 tag:0 length:6 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ObjectIdentifier @2
--- FAIL: TestEtsiTypeAsQcStmt (0.00s)
    lint_qcstatem_etsi_type_as_statem_test.go:36: ../testlint/testCerts/QcStmtEtsiTaggedValueCert20.pem: expected error, got NA
EtsiQcsQcCompliance QCStatement must not contain a statementInfo
asn1: structure error: sequence tag mismatch
--- FAIL: TestEtsiQcCompliance (0.00s)
    lint_qcstatem_qccompliance_valid_test.go:37: ../testlint/testCerts/QcStmtEtsiQcComplWithNonEmptyStmtInfoCert19.pem: expected error, got NA
    lint_qcstatem_qccompliance_valid_test.go:37: ../testlint/testCerts/QcStmtEtsiWrongEncodingCert01.pem: expected error, got NA
asn1: structure error: tags don't match (16 vs {class:0 tag:6 length:7 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2
asn1: syntax error: sequence truncated
--- FAIL: TestEtsiQcType (0.00s)
    lint_qcstatem_qctype_valid_test.go:36: ../testlint/testCerts/QcStmtEtsiMissingSeqForQcTypesCert18.pem: expected error, got NA
    lint_qcstatem_qctype_valid_test.go:36: ../testlint/testCerts/QcStmtEtsiMissingOidCert09.pem: expected error, got NA
FAIL
exit status 1
FAIL	github.com/zmap/zlint/lints	0.207s
```

### PR DESCRIPTION
**Pull request by cpu**
### chore: update to Go 1.15

This switches CI and `go.mod` to use the latest major Go release stream, 1.15.x.

### lints: drop one ETSI test case.

Updates in Go 1.15 mean that an error test case that was used by `v2/lints/etsi/lint_qcstatem_qccompliance_valid_test.go` now panics during parse.

Since we expect the standard library to throw an error for this case now instead of the ZLint lint we can remove the test case.

Resolves #461

### deps: update ZCrypto to latest.

Pulls in ZCrypto at https://github.com/zmap/zcrypto/commit/3719af1573cf8a5e8cfad555065be8b00a5a6d8e, also switched to Go 1.15 & Github Actions, plus a few newer deps.

### Reworked `n_san_iana_pub_suffix_empty`.

While looking at this lint I noticed it has some weird behaviour:

* It could only flag at most one info result per cert.
* It didn't include the name that tripped the result in the details.
* It would return NA for a whole cert if one name failed to parse but with a different error than the one used to determine it's a suffix.

I've updated the implementation to address all of the above. It collects up a list of bad names per-cert, includes them in a details message, and doesn't return NA for parse errors unrelated to suffixes. The unit tests were also not table driven so I rewrote those quickly and included a test case based on my integration test update and a test case with multiple bare public suffixes.

### Updated integration test data.

<details>
<summary>
Here's the story about the expected integration test data change for `n_san_iana_pub_suffix_empty` with lots of detail on the debugging process (half so I can remember it for myself next time, half since it might be useful to new contributors).  TL;DR - old info result behaviour for one cert in the corpus was a bug we accidentally fixed by updating ZCrypto and in turn publicsuffix-go.
</summary>

First to find out what certificate changed from an info result to a pass result I ran the integration tests with `-fingerprintSummary` for just that one lint with both the ZCrypto version in this branch and the one on master.

```
make integration INT_FLAGS="-fingerprintSummary -lintFilter='n_san_iana_pub_suffix_empty'"
```

I cut out the fingerprint summary and diff'd the output between versions to spot the one certificate FP that disappeared with the updated ZCrypto. It was [`d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc`](https://censys.io/certificates/d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc
).

Next I ran the `certByFP.sh` script to pull out that cert from the corpus and get a link to it on Censys.

```
./integration/certByFP.sh d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc
<snipped>
https://censys.io/certificates/d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc
```

Then I ran the lint with the old ZCrypto in [`dlv`](https://github.com/go-delve/delve) and set a breakpoint in the lint.

```
dlv debug ./cmd/zlint -- -includeNames='n_san_iana_pub_suffix_empty' -pretty d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc.pem
break pubsuffix.Execute
```

I stepped through until there was a parse error and printed it:

```
(dlv) p parsedName
github.com/zmap/zcrypto/x509.ParsedDomainName {
	DomainString: "www.theaterpreise.ch\n\n",
	ParsedDomain: *github.com/weppos/publicsuffix-go/publicsuffix.DomainName nil,
	ParseError: error(*errors.errorString) *{
		s: "www.theaterpreise.ch\n\n is a suffix",},}
```

It's a borked DNS SAN with two trailing newlines that was incorrectly deemed a suffix by publicsuffix-go.

Repeating the process with the updated ZCrypto/publicsuffix-go:

```
(dlv) p parsedName
github.com/zmap/zcrypto/x509.ParsedDomainName {
	DomainString: "www.theaterpreise.ch\n\n",
	ParsedDomain: *github.com/weppos/publicsuffix-go/publicsuffix.DomainName {
		TLD: "ch\n\n",
		SLD: "theaterpreise",
		TRD: "www",
		Rule: *(*"github.com/weppos/publicsuffix-go/publicsuffix.Rule")(0xc000108e40),},
	ParseError: error nil,}
```

No more parse error, just a whacky TLD with two newlines. This shouldn't return an info result for `n_san_iana_pub_suffix_empty` and now with updated deps it doesn't. Mystery solved.
</details>

### CODE REVIEW

**Comment by cpu** [comment]
Looks like there's one small delta in the integration test data to chase down:
>  corpus_test.go:164: expected lint "n_san_iana_pub_suffix_empty" to have result
>      fatals: 0    errs: 0    warns: 0    infos: 35   
>  got 
>      fatals: 0    errs: 0    warns: 0    infos: 34  

I think this is because of ZCrypto bumping the public suffix data dependency. I'm out of steam to fix things for today, will pick this up again ~tomorrow w/ the v3.0.0 release work.

**Comment by cpu** [comment]
>  I think this is because of ZCrypto bumping the public suffix data dependency.

This was a correct guess. Fixed in 796c836, updated PR description with the gory details. Bonus: I fixed a couple linter bugs.

**Review by zakird — APPROVED** [review]
Looks solid, thanks!

**Comment by cpu** [comment]
Thanks for the quick review :pray:

**Pull request merged**
